### ISSUE TITLE
Firestore demo docs

### ISSUE THREAD

**Issue by ranmacar** [deg/re-frame-firebase#21]
Hi,

I have tried to run the firestore example, and it does work, but only a few little fixes. Probably just needs to be mentioned in the docs.

1. remove -SNAPSHOT from the dependency (new to clojure, is it a known issue / optimization?)
2. add the firestore.api-keys namespace, or include it in some other way. Obviously you can't commit your credentials here, but a dummy file would be appreciated. Especially since the firestore init is different from the firebase init used in the main docs (needs projectId)
3. you probably need to run the firebase init command at some point to make it work. It's documented on the firebase side, but a little mention wouldn't hurt :)

thanks!

**Comment by deg** [comment]
@gabrielsimoes - do you want to tackle this one?

**Comment by gabrielsimoes** [comment]
Sorry for the long delay, but I've made some improvements and will send a PR soon.
