### ISSUE TITLE
Deriving reagent dependency from re-frame?

### ISSUE THREAD

**Issue by shen-tian** [deg/re-frame-firebase#24]
Noticed this by accident that the project I'm working on is using React 16 rather than 15.

`lein deps :tree` showed this was being pulled in via `reagent 0.8` via `re-frame-firebase`. Latest re-frame itself is using `reagent 0.7`.

Suggestion: drop the explicit `reagent` dependency unless there's a good reason to need the newest version?

**Comment by deg** [comment]
This makes sense. I don't remember why I had originally added the explicit dependency on reagent, but it does not seem like it should be needed.

If you have time to make the change, please verify that it doesn't break `examples/firestore` or anything else obvious, then send me a PR.
