### ISSUE TITLE
Support firebase...update() for multiple & selective value writes

### ISSUE THREAD

**Issue by benzenwen** [deg/re-frame-firebase#32]
Per this: 
https://firebase.google.com/docs/reference/js/firebase.database.Reference#update

I have a pull request if this is interesting to others.  I have been using it successfully for a week.

**Comment by deg** [comment]
I'm not using this feature myself, but it sounds interesting.
If you have a PR ready to go, I'm happy to take a look.

**Comment by benzenwen** [comment]
Thank you for being open to a PR. And of course for writing and maintaining the original code!  Let me level up to master and send the PR.

**Comment by benzenwen** [comment]
Duplicate of #33
