### ISSUE TITLE
Twitter :redirect auth fails quietly on existing user

### ISSUE THREAD

**Issue by deg** [deg/re-frame-firebase#5]
If a user has previously logged via another authorization provider, then `:redirect` authorization via Twitter will fail with no error or warning.

To reproduce:

- Delete your user from the firebase app
- Login with github
- Logout
- Login with Github, redirect. You will see no error, but not be logged in.

It is likely that the best (or only) way to fix this problem is by implementing account linking. See issue [#3 Link Multiple Auth Providers](https://github.com/deg/re-frame-firebase/issues/3)

**Comment by pbzdyl** [comment]
For the record it looks that `com.degel.re-frame-firebase/init` would need to check for [`firebase.auth.Auth#getRedirectResult`](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#getRedirectResult) and handle the auth error in `.catch`.

**Comment by deg** [comment]
Thanks!

**Comment by pbzdyl** [comment]
If you don't mind I can submit a patch soon!

**Comment by deg** [comment]
Cool, thanks.
